apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: myapp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: myapp
        image: kunlawit26acr.azurecr.io/dejango/myapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: myapp_remotexxx03
